export default {
    BASKET_UPDATE: "BASKET_UPDATE",
    BASKET_REMOVE: "BASKET_REMOVE",
    BASKET_PUSH: "BASKET_PUSH",
    BASKET_CLEAR: "BASKET_CLEAR",

    BASKET_REQUEST: "BASKET_REQUEST",
    BASKET_RESPONSE: "BASKET_RESPONSE",
    BASKET_ERROR: "BASKET_ERROR",

    CONTACT_FORM_THANKS_ON: "CONTACT_FORM_THANKS_ON",
    CONTACT_FORM_THANKS_OFF: "CONTACT_FORM_THANKS_OFF",
    CONTACT_FORM_RESPONSE_THANKS: "CONTACT_FORM_RESPONSE_THANKS",

    CONTACT_FORM_FETCHING_ON: "CONTACT_FORM_FETCHING_ON",
    CONTACT_FORM_FETCHING_OFF: "CONTACT_FORM_FETCHING_OFF",
    CONTACT_FORM_RESPONSE_FETCHING: "CONTACT_FORM_RESPONSE_FETCHING",
};
